### ISSUE TITLE
Sample config needed

### ISSUE THREAD

**Issue by ifeign** [jhurliman/homebridge-frontpoint#1]
Hi, I was wondering if you could provide a config.json for your plugin. I'm fairly new to homebridge so I'm not quite sure how to use your particular plugin with my Frontpoint system.

**Comment by SqueakyFox1001** [comment]
Hi ifeign,

Here's the section that I added to my config.json in order to get it to work. 

       {
            "platform": "homebridge-frontpoint.FrontPoint",
            "name": "FrontPoint",
            "username": "ENTER YOUR USERNAME",
            "password": "ENTER YOUR PASSWORD"
        }

Thanks,

**Comment by ifeign** [comment]
Awesome! Thank you for this.

**Comment by jhurliman** [comment]
Thanks! This is now fixed: https://github.com/jhurliman/homebridge-frontpoint/commit/bfd3ed8fcddadb0b54eca8e64689bf54d3c04adc
