### ISSUE TITLE
Extend config to support "silent arm" and "no entry delay" preferences per arming mode

### ISSUE THREAD

**Issue by jdshkolnik** [jhurliman/homebridge-frontpoint#7]
I personally prefer silent arming for home and night but I never use "no entry delay" or my kids' nanny will set it off every morning when she arrives.

I'd propose silent arming as the default for home and night and never default to "no entry delay" since that'd be an unpleasant surprise. A user could override that for each mode in the plugin config.

```
{
    "platform": "FrontPoint",
    "name": "Security System",
    "username": "ENTER YOUR_USERNAME",
    "password": "ENTER YOUR PASSWORD",
    "armingModes": {
        "away": {
            "noEntryDelay": false,
            "silentArming": false
        },
        "night": {
            "noEntryDelay": false,
            "silentArming": true
        },
        "stay": {
            "noEntryDelay": false,
            "silentArming": true
        }
    }
}
```

**Comment by fenway062213** [comment]
This is a great idea. I’ve tried adding it to my config file and it doesn’t seem to be working...is it working for you?

**Comment by jdshkolnik** [comment]
@fenway062213 This is a proposed enhancement rather than something already working. I’ll take a stab at this once @jhurliman signs off so as to not waste my time.

**Comment by fenway062213** [comment]
@jdshkolnik gotcha. It’s a great idea. I would love to see this working. I’ve always wanted to be able to take advantage of night mode on my alarm via Homebridge. We use the no entry delay option at night, so having a way to set that from the Home app would be awesome.

**Comment by jdshkolnik** [comment]
@jhurliman ?

**Comment by ifeign** [comment]
I tried jdshkolnik's version and it worked fine. However, I can't install that through my current setup using the Homebridge UI plugin (unless someone can help? I installed Homebridge with Docker this time around). I was excited to see that your plugin was seemingly updated to support these arming features, yet they do not appear to work.

**Comment by jdshkolnik** [comment]
@ifeign It won't work until @jhurliman updates [the npm package](https://www.npmjs.com/package/homebridge-frontpoint).

**Comment by jhurliman** [comment]
Done

**Comment by fenway062213** [comment]
Awesome. So now what do we need to do - update the plugin and add those lines to the json to get this to work?

**Comment by fenway062213** [comment]
In my eagerness to try this out, I updated the plugin and inserted the updated lines into the json, with this error message being the result in Terminal. Guess I've jumped the gun and am missing something important? Any help appreciated :)

TypeError: Cannot set property 'noEntryDelay' of undefined
    at new FrontPointPlatform (/usr/local/lib/node_modules/homebridge-frontpoint/index.js:55:44)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:325:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
